### ISSUE TITLE
Can smartsnp be used for pooled sequencing data?

### ISSUE THREAD

**Issue by orijitghosh** [ChristianHuber/smartsnp#1]
Hi,
Can smartsnp be used for pooled-sequencing studies? Suppose the data contains sequencing data from DNA sample from 1000 individuals pooled at a particular generation, where the individual haplotypes will be missing and PLINK .fam file would not have the necessary information. Is there a way to use smartsnp in such a case?
Best,
Arijit

**Comment by ChristianHuber** [comment]
Hi Arijit,
The PCA analysis uses a genotype matrix to place individuals into a 2- (or more) dimensional space, reflecting their genetic similarity. I don't think you can use pooled sequencing data since then the information about individuals and their genetic relationships to each other is lost. Now if you have multiple populations, and within populations data is pooled, then maybe there is a way to compute a PCA of populations. However, I'm not sure what your situation is and what you are aiming to achieve.
Best,
Christian
